version: '3.8'

services:
  ogp-proxy:
    container_name: ogp-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    volumes:
      - ./src:/app/src
      - ./views:/app/views
    ports:
      - 9090:8080
